version: 2.1

orbs:
  ruby: circleci/ruby@2.6.0

jobs:
  build:
    docker:
      - image: cimg/ruby:3.4.2

    working_directory: ~/repo

    steps:
      - checkout
      - ruby/install-deps:
          key: v1-dependencies-{{ checksum "Gemfile.lock" }}
          include-branch-in-cache-key: false

      - run:
          name: set up database
          command: bundle exec rake db:drop db:create db:migrate

      - run:
          name: run tests
          command: |
            mkdir -p /tmp/test-results
            bundle exec rspec --format progress \
                            --format RspecJunitFormatter \
                            --out /tmp/test-results/rspec.xml \
                            $(circleci tests glob "spec/**/*_spec.rb")

      - store_test_results:
          path: /tmp/test-results
      - store_artifacts:
          path: /tmp/test-results
          destination: test-results

workflows:
  build_and_test:
    jobs:
      - build
